trigger: 
- main
pr: none
jobs:
- job: DockerBuild

  pool:
    vmImage: 'ubuntu-latest'
  variables:
    REPOSITORY: 'nikeshi/testing1'
    imageName: 'nikeshi/$(REPOSITORY):$(Build.Buildid)' 
  steps:
  - task: Docker@2
    displayName: 'Build and Docker Image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'Docker Hub'
      command: build
      repository: $(REPOSITORY)
      Dockerfile: 'Hello-world-service/Dockerfile' 
      imageName: $(imageName)
      buildContext: 'Hello-world-service/'
      tags: |
        $(Build.Buildid)

  - task: Docker@2
    displayName: 'Push the Docker image to Dockerhub'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'Docker Hub'
      repository: $(REPOSITORY)
      command: push
      imageName: $(imageName)
  - script: |
      docker run -d -p  8080:9090 $(REPOSITORY):latest &
      sleep 15
      curl http://localhost:8080/greeting