trigger: 
- main
pr: none
jobs:
- job: DockerBuild

  pool:
    vmImage: 'ubuntu-latest'
  variables:
    imageName: 'pipelines-hello-docker'
  steps:

  - task: Docker@2
    displayName: 'Build Init Docker Image'
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: 'Hello-world-service/Dockerfile'
      buildContext: '.'
      tags: |
        latest

  - script: |
      curl http://localhost:8080/greeting
