trigger: 
- main
pr: none
jobs:
- job: DockerBuild

  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Hub'
      repository: 'nikeshi/testing1'
      command: 'buildAndPush'
      Dockerfile: 'Hello-world-service/Dockerfile'
      buildContext: 'Hello-world-service/'
      tag: |
        v1

  - script: |
      docker run -d -p 8080:8080 nikeshi/testing1:v1
      sleep 120
      curl http://localhost:8080/greeting