trigger: 
- main
pr: none
jobs:
- job: DockerBuild

  pool:
    vmImage: 'ubuntu-latest'
  variables:
    imageName: 'helloworld'
    REPOSITORY: 'nikeshi/testing1'
    
  steps:
  - task: Docker@2
    displayName: 'Build and Push Docker Image'
    inputs:
      dockerRegistryEndpoint: 'Docker Hub'
      command: buildAndPush
      repository: $(REPOSITORY)
      Dockerfile: 'Hello-world-service/Dockerfile' 
      imageName: '$(imageName)'
      buildContext: 'Hello-world-service/'
      tags: |
        latest
  - script: |
      docker run -d -p 8080:8080 HelloWorld-docker.azurecr.io/$(REPOSITORY):latest &
      sleep 10
      curl http://localhost:8080/greeting