trigger: 
- main
pr: none
jobs:
- job: DockerBuild

  pool:
    vmImage: 'ubuntu-latest'
  variables:
    imageName: 'pipelines-hello-docker'
  steps:
  - script: |
      docker login -u nikeshi -p nikeshi@321
  - task: Docker@2
    displayName: 'Build and push Docker Image'
    inputs:
      repository: $(imageName)
      command: buildAndPush
      Dockerfile: 'Hello-world-service/Dockerfile'
      buildContext: '.'
      tags: |
        latest

  - script: |
      docker run -d -p  8080:9090 $(imageName)
      curl http://localhost:8080/greeting
