trigger: 
- main
pr: none
jobs:
- job: DockerBuild

  pool:
    vmImage: 'ubuntu-latest'
  variables:
    REPOSITORY: 'nikeshi/testing1'
    imageName: 'nikeshi/$(REPOSITORY):$(Build.Buildid)' 
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Hub'
      repository: 'nikeshi/testing1'
      command: 'buildAndPush'
      Dockerfile: 'Hello-world-service/Dockerfile'
      buildContext: 'Hello-world-service/''
  - script: |
      docker run -d -p  8080:9090 nikeshi/testing1:$(Build.BuildId)
      sleep 60
      curl http://localhost:8080/greeting