apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: my-kubernetes
  name: pod-reader
rules:
- apiGroups: rbac.authorization.k8s.io
  resources: ["pods"]
  verbs: ["get", "watch", "list","create"]
- apiGroups: 
  - apps
  resources: ["deployments"]
  verbs: ["get", "update", "list","create","patch","edit"]