apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: my-kubernetes
  name: pod-reader
rules:
- apiGroups: ["rbac.authorization.k8s.io"] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list","create"]