trigger: 
- main
pr: none
jobs:
- deployment: Deploy
  displayName: Deploy
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: KubernetesManifest@0
          inputs:
            action: 'deploy'
            kubernetesServiceConnection: 'Kubernetes'
            namespace: 'my-kubernetes'
            manifests: 'deployment.yaml'